### ISSUE TITLE
Fix parsing of immosuche.degewo.de

### ISSUE THREAD

**Issue by noyainrain** [noyainrain/flatdir#10]
Parsing immosuche.degewo.de fails with `No a/div[2]/ul[2]/li[1]/span in <article class="article-list__item article-list__item--immosearch" />`.

**Comment by noyainrain** [comment]
This is caused by the rooms ul position depending on tags.

**Comment by andylundqvist** [comment]
As of Feb. 28 2025 [immosuche.degewo.de](immosuche.degewo.de) does not work properly anymore on [berlin.flat.directory](https://berlin.flat.directory/). The listing on Flatdir seems to still be correct but if you follow a link from Flatdir it leads to the main page / search page on the Degewo site and does not link directly to the specific flat ad.
